### ISSUE TITLE
mcinstall fails with error - urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by sackh** [deeplook/mcinstall#18]
python version - 3.8.2

ERROR: 
```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/mcinstall", line 11, in <module>
    load_entry_point('mcinstall==0.3.0', 'console_scripts', 'mcinstall')()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mcinstall.py", line 338, in main
    inst.install_miniconda()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mcinstall.py", line 127, in install_miniconda
    resp = request.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

I think I know the fix below is SO to fix this:
https://stackoverflow.com/questions/13303449/urllib2-httperror-http-error-403-forbidden

**Comment by sackh** [comment]
closing this as this is fixed in #19.
